### ISSUE TITLE
Some `toy` features broken in v0.9.0

### ISSUE THREAD

**Issue by keith-hall** [fancy-regex/fancy-regex#90]
Unfortunately it looks like I broke some features of the `toy` example when adding support for `\K`.
```sh
fancy-regex on  main is 📦 v0.9.0 via 🦀 v1.60.0 
✦ ❯ RUST_BACKTRACE=1 cargo run --example toy trace '\d*' '1122 33'
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/toy trace '\d*' '1122 33'`
pos	instruction
0	0 Delegate { inner: ^\d*, inner1: None, start_group: 0, end_group: 0 }
4	1 End
saves: []
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 1', src/vm.rs:305:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:85:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/slice/index.rs:189:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/vec/mod.rs:2531:9
   6: fancy_regex::vm::State::get
             at ./src/vm.rs:305:9
   7: fancy_regex::vm::run
             at ./src/vm.rs:442:33
   8: fancy_regex::vm::run_trace
             at ./src/vm.rs:403:5
   9: toy::main
             at ./examples/toy.rs:76:21
  10: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It would be great to get some `toy` runs added to CI to help prevent breakages like these :)

**Comment by keith-hall** [comment]
Solved by https://github.com/fancy-regex/fancy-regex/pull/91 👍
